import path from 'node:path';
import { createServer } from 'vite';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
const root = path.resolve('samples');
const server = await createServer({ appType: 'custom', root, logLevel: 'silent', plugins: [react(), tailwindcss()], resolve: { alias: { '@': root } }, server: { middlewareMode: true } });
await server.transformRequest('/components/ui/badge.tsx');
const result = await server.transformRequest('/.shadcn-tweaker/preview-styles.css?direct');
const code = result?.code ?? '';
console.log('E: module-first → length', code.length, 'utility hits', (code.match(/\.rounded-full|\.inline-flex|\.bg-primary/g) ?? []).length);
await server.close();
process.exit(0);
