export {
  analyzePixelInspector,
  applyMotion,
  applyPixelInspector,
  applyVariantGeneration,
  buildMotionOutput,
  createMotionPreset,
  createPixelInspectorPreset,
  deleteMotionPreset,
  deletePixelInspectorPreset,
  generateBrailleLoader,
  getBrailleLoaderPresets,
  getComponentPreviewManifest,
  getMotionDefaults,
  getMotionPresets,
  getMotionSlots,
  getPixelInspectorPresets,
  getStudioSummary,
  previewMotion,
  previewPixelInspector,
  updateWorkspaceConfig,
} from './api/client.js';
export type {
  BrailleLoaderCustomization,
  BrailleLoaderGenerated,
  BrailleLoaderPreset,
  BrailleLoaderReducedMotionMode,
  ComponentPreviewManifest,
  ComponentPreviewRequest,
  MotionApplyResult,
  MotionEasing,
  MotionOutput,
  MotionPhase,
  MotionPreset,
  MotionReducedMotionBehavior,
  MotionSettings,
  MotionSlot,
  MotionTransformOrigin,
  PixelInspectorAnalysis,
  PixelInspectorApplyRequest,
  PixelInspectorApplyResult,
  PixelInspectorClassCandidate,
  PixelInspectorControlGroup,
  PixelInspectorDraft,
  PixelInspectorPreviewRequest,
  PixelInspectorSaveMode,
  Preset,
  PreviewDensity,
  PreviewState,
  PreviewTheme,
  PreviewViewport,
  StudioSummary,
  WorkspaceConfig,
} from './types/index.js';
export type { WorkbenchArea } from './workbench.js';
export {
  getWorkbenchAreaMeta,
  WORKBENCH_AREAS,
} from './workbench.js';
